//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonobo.Git.Server.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonobo.Git.Server.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account with this username already exists..
        /// </summary>
        public static string Account_Create_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_Create_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account information.
        /// </summary>
        public static string Account_Create_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Create_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string Account_Create_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Create_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Account_Create_Email {
            get {
                return ResourceManager.GetString("Account_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Account_Create_Name {
            get {
                return ResourceManager.GetString("Account_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Account_Create_Password {
            get {
                return ResourceManager.GetString("Account_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Account_Create_Submit {
            get {
                return ResourceManager.GetString("Account_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user was created successfully..
        /// </summary>
        public static string Account_Create_Success {
            get {
                return ResourceManager.GetString("Account_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        public static string Account_Create_Surname {
            get {
                return ResourceManager.GetString("Account_Create_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New Account.
        /// </summary>
        public static string Account_Create_Title {
            get {
                return ResourceManager.GetString("Account_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_Create_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Create_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Account_Create_Username {
            get {
                return ResourceManager.GetString("Account_Create_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t delete yourself..
        /// </summary>
        public static string Account_Delete_DeleteCurrentUser {
            get {
                return ResourceManager.GetString("Account_Delete_DeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user was deleted..
        /// </summary>
        public static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Account_Detail_Back {
            get {
                return ResourceManager.GetString("Account_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Account_Detail_Delete {
            get {
                return ResourceManager.GetString("Account_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Account_Detail_Edit {
            get {
                return ResourceManager.GetString("Account_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Account_Detail_Email {
            get {
                return ResourceManager.GetString("Account_Detail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Account_Detail_Name {
            get {
                return ResourceManager.GetString("Account_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string Account_Detail_Roles {
            get {
                return ResourceManager.GetString("Account_Detail_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        public static string Account_Detail_Surname {
            get {
                return ResourceManager.GetString("Account_Detail_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Detail.
        /// </summary>
        public static string Account_Detail_Title {
            get {
                return ResourceManager.GetString("Account_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Account_Detail_Username {
            get {
                return ResourceManager.GetString("Account_Detail_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Account_Edit_Back {
            get {
                return ResourceManager.GetString("Account_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Account_Edit_Cancel {
            get {
                return ResourceManager.GetString("Account_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t remove yourself from administrators..
        /// </summary>
        public static string Account_Edit_CannotRemoveYourselfFromAdminRole {
            get {
                return ResourceManager.GetString("Account_Edit_CannotRemoveYourselfFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string Account_Edit_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Edit_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string Account_Edit_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_Edit_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Account_Edit_Email {
            get {
                return ResourceManager.GetString("Account_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Account_Edit_Name {
            get {
                return ResourceManager.GetString("Account_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string Account_Edit_NewPassword {
            get {
                return ResourceManager.GetString("Account_Edit_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password should not be empty..
        /// </summary>
        public static string Account_Edit_OldPasswordEmpty {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not match the current password..
        /// </summary>
        public static string Account_Edit_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string Account_Edit_Roles {
            get {
                return ResourceManager.GetString("Account_Edit_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrators have access to all repositories and are allowed to do all operations with repositories, teams and users..
        /// </summary>
        public static string Account_Edit_RolesHint {
            get {
                return ResourceManager.GetString("Account_Edit_RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Account_Edit_Submit {
            get {
                return ResourceManager.GetString("Account_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        public static string Account_Edit_Surname {
            get {
                return ResourceManager.GetString("Account_Edit_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit User Account.
        /// </summary>
        public static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_Edit_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Edit_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was updated successfully..
        /// </summary>
        public static string Account_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Account_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Account_Edit_Username {
            get {
                return ResourceManager.GetString("Account_Edit_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new user.
        /// </summary>
        public static string Account_Index_Create {
            get {
                return ResourceManager.GetString("Account_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Account_Index_Title {
            get {
                return ResourceManager.GetString("Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Account_Index_Users {
            get {
                return ResourceManager.GetString("Account_Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Delete_Back {
            get {
                return ResourceManager.GetString("Delete_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you really want to delete {0}?.
        /// </summary>
        public static string Delete_ConfirmationText {
            get {
                return ResourceManager.GetString("Delete_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Confirmation.
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;A request has been received to reset your password. 
        ///                           If you did not initiate the request, then please ignore this email.&lt;/p&gt;
        ///                           &lt;p&gt;Please click the following link to reset your password:&lt;/p&gt;.
        /// </summary>
        public static string Email_PasswordReset_Body {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bonobo - Password Reset Request.
        /// </summary>
        public static string Email_PasswordReset_Title {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks!.
        /// </summary>
        public static string Home_About_Thanks {
            get {
                return ResourceManager.GetString("Home_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when processing your request. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_Error_Text {
            get {
                return ResourceManager.GetString("Home_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An Error Occurred.
        /// </summary>
        public static string Home_Error_Title {
            get {
                return ResourceManager.GetString("Home_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to send email. Validate SMTP settings..
        /// </summary>
        public static string Home_ForgotPassword_EmailError {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email sent.
        /// </summary>
        public static string Home_ForgotPassword_EmailSuccess {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgotten Password Failed. Please correct errors and try again..
        /// </summary>
        public static string Home_ForgotPassword_Failed {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password.
        /// </summary>
        public static string Home_ForgotPassword_ForgotPassword {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgotten Password.
        /// </summary>
        public static string Home_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Home_ForgotPassword_Username {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find username.
        /// </summary>
        public static string Home_ForgotPassword_UserNameFailure {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_UserNameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Information.
        /// </summary>
        public static string Home_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Home_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Home_LogOn_Failed {
            get {
                return ResourceManager.GetString("Home_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password?.
        /// </summary>
        public static string Home_LogOn_ForgotPassword {
            get {
                return ResourceManager.GetString("Home_LogOn_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string Home_LogOn_LogOn {
            get {
                return ResourceManager.GetString("Home_LogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Home_LogOn_Password {
            get {
                return ResourceManager.GetString("Home_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me?.
        /// </summary>
        public static string Home_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Home_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string Home_LogOn_Title {
            get {
                return ResourceManager.GetString("Home_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Home_LogOn_Username {
            get {
                return ResourceManager.GetString("Home_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or password provided is incorrect..
        /// </summary>
        public static string Home_LogOn_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_LogOn_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The page you were looking for wasn&apos;t found. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_PageNotFound_Text {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 404 Page Not Found.
        /// </summary>
        public static string Home_PageNotFound_Title {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string Home_ResetPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("Home_ResetPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to reset password.
        /// </summary>
        public static string Home_ResetPassword_Failed {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Home_ResetPassword_Password {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Password.
        /// </summary>
        public static string Home_ResetPassword_ResetPassword {
            get {
                return ResourceManager.GetString("Home_ResetPassword_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset.
        /// </summary>
        public static string Home_ResetPassword_Success {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Password.
        /// </summary>
        public static string Home_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Home_ResetPassword_Username {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A server error occurred when processing your request. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_ServerError_Text {
            get {
                return ResourceManager.GetString("Home_ServerError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500 Server Error.
        /// </summary>
        public static string Home_ServerError_Title {
            get {
                return ResourceManager.GetString("Home_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have permission for the selected action or page..
        /// </summary>
        public static string Home_Unauthorized_Text {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unauthorized.
        /// </summary>
        public static string Home_Unauthorized_Title {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item wasn&apos;t found.
        /// </summary>
        public static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The item you were looking for wasn&apos;t found..
        /// </summary>
        public static string Item_NotFound_Text {
            get {
                return ResourceManager.GetString("Item_NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Settings.
        /// </summary>
        public static string Layout_AccountSettings {
            get {
                return ResourceManager.GetString("Layout_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administration.
        /// </summary>
        public static string Layout_Administration {
            get {
                return ResourceManager.GetString("Layout_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Layout_AdministrationGlobalSettings {
            get {
                return ResourceManager.GetString("Layout_AdministrationGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Layout_AdministrationRepositories {
            get {
                return ResourceManager.GetString("Layout_AdministrationRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams.
        /// </summary>
        public static string Layout_AdministrationTeams {
            get {
                return ResourceManager.GetString("Layout_AdministrationTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Layout_AdministrationUsers {
            get {
                return ResourceManager.GetString("Layout_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All rights reserved..
        /// </summary>
        public static string Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        public static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string Layout_LogOn {
            get {
                return ResourceManager.GetString("Layout_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Layout_Repositories {
            get {
                return ResourceManager.GetString("Layout_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bonobo Git Server.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Repository_AddressBar_Root {
            get {
                return ResourceManager.GetString("Repository_AddressBar_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrators have full access to the repository. They can modify repository metadata or delete the repository..
        /// </summary>
        public static string Repository_AdministratorsHint {
            get {
                return ResourceManager.GetString("Repository_AdministratorsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If anonymous access is allowed, everyone can pull or clone the repository and view repository metadata. Push is available only if set in Global Settings..
        /// </summary>
        public static string Repository_AllowAnonymousHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows anonymous users to push to this repository if anonymous access is granted. If &quot;Global&quot; is selected the option set under your global settings is used..
        /// </summary>
        public static string Repository_AllowAnonymousPushHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousPushHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record user that pushed commits to the server.
        /// </summary>
        public static string Repository_AuditPushUserHint {
            get {
                return ResourceManager.GetString("Repository_AuditPushUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Repository_Back {
            get {
                return ResourceManager.GetString("Repository_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blame.
        /// </summary>
        public static string Repository_Blame_Title {
            get {
                return ResourceManager.GetString("Repository_Blame_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository cloning was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_Clone_Fail {
            get {
                return ResourceManager.GetString("Repository_Clone_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clone.
        /// </summary>
        public static string Repository_Clone_Submit {
            get {
                return ResourceManager.GetString("Repository_Clone_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository was cloned successfully..
        /// </summary>
        public static string Repository_Clone_Success {
            get {
                return ResourceManager.GetString("Repository_Clone_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clone Repository.
        /// </summary>
        public static string Repository_Clone_Title {
            get {
                return ResourceManager.GetString("Repository_Clone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added.
        /// </summary>
        public static string Repository_Commit_Added {
            get {
                return ResourceManager.GetString("Repository_Commit_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author.
        /// </summary>
        public static string Repository_Commit_Author {
            get {
                return ResourceManager.GetString("Repository_Commit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar.
        /// </summary>
        public static string Repository_Commit_AuthorAvatar {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Repository_Commit_AuthorEmail {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes.
        /// </summary>
        public static string Repository_Commit_Changes {
            get {
                return ResourceManager.GetString("Repository_Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copied.
        /// </summary>
        public static string Repository_Commit_Copied {
            get {
                return ResourceManager.GetString("Repository_Commit_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Repository_Commit_Date {
            get {
                return ResourceManager.GetString("Repository_Commit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        public static string Repository_Commit_Deleted {
            get {
                return ResourceManager.GetString("Repository_Commit_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commit Detail.
        /// </summary>
        public static string Repository_Commit_Detail {
            get {
                return ResourceManager.GetString("Repository_Commit_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Repository_Commit_Details {
            get {
                return ResourceManager.GetString("Repository_Commit_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commit.
        /// </summary>
        public static string Repository_Commit_ID {
            get {
                return ResourceManager.GetString("Repository_Commit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Repository_Commit_Message {
            get {
                return ResourceManager.GetString("Repository_Commit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modified.
        /// </summary>
        public static string Repository_Commit_Modified {
            get {
                return ResourceManager.GetString("Repository_Commit_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not declared.
        /// </summary>
        public static string Repository_Commit_NoMessageDeclared {
            get {
                return ResourceManager.GetString("Repository_Commit_NoMessageDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parents.
        /// </summary>
        public static string Repository_Commit_Parents {
            get {
                return ResourceManager.GetString("Repository_Commit_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renamed.
        /// </summary>
        public static string Repository_Commit_Renamed {
            get {
                return ResourceManager.GetString("Repository_Commit_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tree.
        /// </summary>
        public static string Repository_Commit_TreeID {
            get {
                return ResourceManager.GetString("Repository_Commit_TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type Changed.
        /// </summary>
        public static string Repository_Commit_TypeChanged {
            get {
                return ResourceManager.GetString("Repository_Commit_TypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commits.
        /// </summary>
        public static string Repository_Commits_Title {
            get {
                return ResourceManager.GetString("Repository_Commits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Repository_Create_Back {
            get {
                return ResourceManager.GetString("Repository_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A directory with this name already exists in your repository folder. Delete this directory or choose another name and try again..
        /// </summary>
        public static string Repository_Create_DirectoryExists {
            get {
                return ResourceManager.GetString("Repository_Create_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_Create_Fail {
            get {
                return ResourceManager.GetString("Repository_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository with selected name already exists..
        /// </summary>
        public static string Repository_Create_Failure {
            get {
                return ResourceManager.GetString("Repository_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository information.
        /// </summary>
        public static string Repository_Create_Informations {
            get {
                return ResourceManager.GetString("Repository_Create_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Name&quot; shouldn&apos;t contain only whitespace characters..
        /// </summary>
        public static string Repository_Create_NameFailure {
            get {
                return ResourceManager.GetString("Repository_Create_NameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Repository_Create_Submit {
            get {
                return ResourceManager.GetString("Repository_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository was created successfully..
        /// </summary>
        public static string Repository_Create_Success {
            get {
                return ResourceManager.GetString("Repository_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to &quot;{0}&quot;.
        /// </summary>
        public static string Repository_Create_Success_Go_To {
            get {
                return ResourceManager.GetString("Repository_Create_Success_Go_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New Repository.
        /// </summary>
        public static string Repository_Create_Title {
            get {
                return ResourceManager.GetString("Repository_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository was deleted successfully..
        /// </summary>
        public static string Repository_Delete_Success {
            get {
                return ResourceManager.GetString("Repository_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrators.
        /// </summary>
        public static string Repository_Detail_Administrators {
            get {
                return ResourceManager.GetString("Repository_Detail_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anonymous push.
        /// </summary>
        public static string Repository_Detail_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Repository_Detail_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anonymous.
        /// </summary>
        public static string Repository_Detail_Anonymous {
            get {
                return ResourceManager.GetString("Repository_Detail_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audit Pushes.
        /// </summary>
        public static string Repository_Detail_AuditPushUser {
            get {
                return ResourceManager.GetString("Repository_Detail_AuditPushUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Repository_Detail_Back {
            get {
                return ResourceManager.GetString("Repository_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Repository_Detail_Delete {
            get {
                return ResourceManager.GetString("Repository_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Repository_Detail_Description {
            get {
                return ResourceManager.GetString("Repository_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Repository_Detail_Detail {
            get {
                return ResourceManager.GetString("Repository_Detail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Repository_Detail_Edit {
            get {
                return ResourceManager.GetString("Repository_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        public static string Repository_Detail_Group {
            get {
                return ResourceManager.GetString("Repository_Detail_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        public static string Repository_Detail_IsCurrentUserAdmin {
            get {
                return ResourceManager.GetString("Repository_Detail_IsCurrentUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use global linkify settings.
        /// </summary>
        public static string Repository_Detail_LinksUseGlobal {
            get {
                return ResourceManager.GetString("Repository_Detail_LinksUseGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Git URL.
        /// </summary>
        public static string Repository_Detail_Location {
            get {
                return ResourceManager.GetString("Repository_Detail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal URL.
        /// </summary>
        public static string Repository_Detail_Location_Personal {
            get {
                return ResourceManager.GetString("Repository_Detail_Location_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo (36x36).
        /// </summary>
        public static string Repository_Detail_Logo_PostedFile {
            get {
                return ResourceManager.GetString("Repository_Detail_Logo_PostedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Repository_Detail_Name {
            get {
                return ResourceManager.GetString("Repository_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string Repository_Detail_No {
            get {
                return ResourceManager.GetString("Repository_Detail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove logo.
        /// </summary>
        public static string Repository_Detail_RemoveLogo {
            get {
                return ResourceManager.GetString("Repository_Detail_RemoveLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Repository_Detail_Status {
            get {
                return ResourceManager.GetString("Repository_Detail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams.
        /// </summary>
        public static string Repository_Detail_Teams {
            get {
                return ResourceManager.GetString("Repository_Detail_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository Detail.
        /// </summary>
        public static string Repository_Detail_Title {
            get {
                return ResourceManager.GetString("Repository_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contributors.
        /// </summary>
        public static string Repository_Detail_Users {
            get {
                return ResourceManager.GetString("Repository_Detail_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Repository_Detail_Yes {
            get {
                return ResourceManager.GetString("Repository_Detail_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Repository_Edit_Back {
            get {
                return ResourceManager.GetString("Repository_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t remove yourself from administrators..
        /// </summary>
        public static string Repository_Edit_CantRemoveYourself {
            get {
                return ResourceManager.GetString("Repository_Edit_CantRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_Edit_Fail {
            get {
                return ResourceManager.GetString("Repository_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid value provided..
        /// </summary>
        public static string Repository_Edit_InvalidAnonymousPushMode {
            get {
                return ResourceManager.GetString("Repository_Edit_InvalidAnonymousPushMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Repository_Edit_Submit {
            get {
                return ResourceManager.GetString("Repository_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Repository.
        /// </summary>
        public static string Repository_Edit_Title {
            get {
                return ResourceManager.GetString("Repository_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository was updated successfully..
        /// </summary>
        public static string Repository_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Repository_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy repository URL.
        /// </summary>
        public static string Repository_Git_Url_Copy {
            get {
                return ResourceManager.GetString("Repository_Git_Url_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to repository.
        /// </summary>
        public static string Repository_Go_To_Dropdown {
            get {
                return ResourceManager.GetString("Repository_Go_To_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        public static string Repository_History_Title {
            get {
                return ResourceManager.GetString("Repository_History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administered Repositories.
        /// </summary>
        public static string Repository_Index_AdministratedRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AdministratedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Repositories.
        /// </summary>
        public static string Repository_Index_AllRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new repository.
        /// </summary>
        public static string Repository_Index_CreateNew {
            get {
                return ResourceManager.GetString("Repository_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string Repository_Index_No {
            get {
                return ResourceManager.GetString("Repository_Index_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Repository_Index_Repositories {
            get {
                return ResourceManager.GetString("Repository_Index_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort Group.
        /// </summary>
        public static string Repository_Index_SortGroup {
            get {
                return ResourceManager.GetString("Repository_Index_SortGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Repository_Index_Title {
            get {
                return ResourceManager.GetString("Repository_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Repository_Index_Yes {
            get {
                return ResourceManager.GetString("Repository_Index_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository Browser.
        /// </summary>
        public static string Repository_Layout_Browse {
            get {
                return ResourceManager.GetString("Repository_Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clone.
        /// </summary>
        public static string Repository_Layout_Clone {
            get {
                return ResourceManager.GetString("Repository_Layout_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commits.
        /// </summary>
        public static string Repository_Layout_Commits {
            get {
                return ResourceManager.GetString("Repository_Layout_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string Repository_Layout_Tags {
            get {
                return ResourceManager.GetString("Repository_Layout_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository requires at least one administrator..
        /// </summary>
        public static string Repository_Needs_Administrator {
            get {
                return ResourceManager.GetString("Repository_Needs_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Group.
        /// </summary>
        public static string Repository_No_Group {
            get {
                return ResourceManager.GetString("Repository_No_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy personal repository URL.
        /// </summary>
        public static string Repository_Personal_Git_Url_Copy {
            get {
                return ResourceManager.GetString("Repository_Personal_Git_Url_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rescan directory.
        /// </summary>
        public static string Repository_Rescan_Directory {
            get {
                return ResourceManager.GetString("Repository_Rescan_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switch current branch.
        /// </summary>
        public static string Repository_SwitchBranch {
            get {
                return ResourceManager.GetString("Repository_SwitchBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string Repository_Tags_Title {
            get {
                return ResourceManager.GetString("Repository_Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams have access to the repository. They can clone, push or pull and view repository metadata. All users in the team can access this repository..
        /// </summary>
        public static string Repository_TeamsHint {
            get {
                return ResourceManager.GetString("Repository_TeamsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author.
        /// </summary>
        public static string Repository_Tree_Author {
            get {
                return ResourceManager.GetString("Repository_Tree_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blame.
        /// </summary>
        public static string Repository_Tree_Blame {
            get {
                return ResourceManager.GetString("Repository_Tree_Blame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blob.
        /// </summary>
        public static string Repository_Tree_Blob {
            get {
                return ResourceManager.GetString("Repository_Tree_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Repository_Tree_CommitDate {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Repository_Tree_CommitMessage {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string Repository_Tree_Download {
            get {
                return ResourceManager.GetString("Repository_Tree_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        public static string Repository_Tree_History {
            get {
                return ResourceManager.GetString("Repository_Tree_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Repository_Tree_Name {
            get {
                return ResourceManager.GetString("Repository_Tree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview of this file is not supported..
        /// </summary>
        public static string Repository_Tree_PreviewNotSupported {
            get {
                return ResourceManager.GetString("Repository_Tree_PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw.
        /// </summary>
        public static string Repository_Tree_RawDisplay {
            get {
                return ResourceManager.GetString("Repository_Tree_RawDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse Repository.
        /// </summary>
        public static string Repository_Tree_Title {
            get {
                return ResourceManager.GetString("Repository_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string Repository_Tree_Zip {
            get {
                return ResourceManager.GetString("Repository_Tree_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users have access to the repository. They can clone, push or pull and view repository metadata..
        /// </summary>
        public static string Repository_UsersHint {
            get {
                return ResourceManager.GetString("Repository_UsersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow push for anonymous repositories.
        /// </summary>
        public static string Settings_Global_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow anonymous registration.
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If checkbox is unchecked, only administrators can add new users and anonymous user registration is disabled..
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow push to create repositories.
        /// </summary>
        public static string Settings_Global_AllowPushToCreate {
            get {
                return ResourceManager.GetString("Settings_Global_AllowPushToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If checkbox is checked, Administrators can push a new repository .
        /// </summary>
        public static string Settings_Global_AllowPushToCreate_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowPushToCreate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow user repository creation.
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If checkbox is unchecked, only administrators can create repositories..
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Settings_Global_DefaultLanguage {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language set by default in the application..
        /// </summary>
        public static string Settings_Global_DefaultLanguage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All repositories are stored in this directory..
        /// </summary>
        public static string Settings_Global_DirectoryHint {
            get {
                return ResourceManager.GetString("Settings_Global_DirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show commit author avatar.
        /// </summary>
        public static string Settings_Global_IsCommitAuthorAvatarVisible {
            get {
                return ResourceManager.GetString("Settings_Global_IsCommitAuthorAvatarVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link Regex.
        /// </summary>
        public static string Settings_Global_LinksRegex {
            get {
                return ResourceManager.GetString("Settings_Global_LinksRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link Url.
        /// </summary>
        public static string Settings_Global_LinksUrl {
            get {
                return ResourceManager.GetString("Settings_Global_LinksUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This uses the C# regex library to parse the provided regex. Capturing groups are supported.
        ///
        ///The pattern is {0} for the whole regex match.
        ///{1} onwards is each capturing group.
        ///
        ///The regular C# string formatting rules apply: To get {} in your link you need to write {{}}..
        /// </summary>
        public static string Settings_Global_LinksUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_LinksUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository Directory.
        /// </summary>
        public static string Settings_Global_RepositoryPath {
            get {
                return ResourceManager.GetString("Settings_Global_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site CSS URL.
        /// </summary>
        public static string Settings_Global_SiteCssUrl {
            get {
                return ResourceManager.GetString("Settings_Global_SiteCssUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL to a CSS file to use for the site.  Site-relative (~) paths are supported..
        /// </summary>
        public static string Settings_Global_SiteCssUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteCssUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site Footer Message.
        /// </summary>
        public static string Settings_Global_SiteFooterMessage {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message displayed in footer area of site pages..
        /// </summary>
        public static string Settings_Global_SiteFooterMessage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site Logo URL.
        /// </summary>
        public static string Settings_Global_SiteLogoUrl {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL to a logo to use for the site.  Site-relative (~) paths are supported..
        /// </summary>
        public static string Settings_Global_SiteLogoUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site Title.
        /// </summary>
        public static string Settings_Global_SiteTitle {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title for this git site..
        /// </summary>
        public static string Settings_Global_SiteTitle_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Settings_Index_Failed {
            get {
                return ResourceManager.GetString("Settings_Index_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Settings_Index_Save {
            get {
                return ResourceManager.GetString("Settings_Index_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Settings_Index_Title {
            get {
                return ResourceManager.GetString("Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings updated successfully..
        /// </summary>
        public static string Settings_Index_UpdateSuccess {
            get {
                return ResourceManager.GetString("Settings_Index_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected path does not exist. Please create the folder or choose a different one..
        /// </summary>
        public static string Settings_RepositoryPathNotExists {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have privileges to write to the folder. Please choose a different one..
        /// </summary>
        public static string Settings_RepositoryPathUnauthorized {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Github.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Team_Create_Back {
            get {
                return ResourceManager.GetString("Team_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New team creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_Create_Fail {
            get {
                return ResourceManager.GetString("Team_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team with selected name already exists. Team wasn&apos;t created..
        /// </summary>
        public static string Team_Create_Failure {
            get {
                return ResourceManager.GetString("Team_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Team_Create_Submit {
            get {
                return ResourceManager.GetString("Team_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The team was created successfully..
        /// </summary>
        public static string Team_Create_Success {
            get {
                return ResourceManager.GetString("Team_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team information.
        /// </summary>
        public static string Team_Create_TeamInformations {
            get {
                return ResourceManager.GetString("Team_Create_TeamInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New Team.
        /// </summary>
        public static string Team_Create_Title {
            get {
                return ResourceManager.GetString("Team_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The team was deleted..
        /// </summary>
        public static string Team_Delete_Success {
            get {
                return ResourceManager.GetString("Team_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Team_Detail_Back {
            get {
                return ResourceManager.GetString("Team_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Team_Detail_Delete {
            get {
                return ResourceManager.GetString("Team_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Team_Detail_Description {
            get {
                return ResourceManager.GetString("Team_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Team_Detail_Edit {
            get {
                return ResourceManager.GetString("Team_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        public static string Team_Detail_Members {
            get {
                return ResourceManager.GetString("Team_Detail_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Team_Detail_Name {
            get {
                return ResourceManager.GetString("Team_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Team_Detail_Repositories {
            get {
                return ResourceManager.GetString("Team_Detail_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team Detail.
        /// </summary>
        public static string Team_Detail_Title {
            get {
                return ResourceManager.GetString("Team_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Team_Edit_Back {
            get {
                return ResourceManager.GetString("Team_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_Edit_Failure {
            get {
                return ResourceManager.GetString("Team_Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string Team_Edit_Submit {
            get {
                return ResourceManager.GetString("Team_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Team.
        /// </summary>
        public static string Team_Edit_Title {
            get {
                return ResourceManager.GetString("Team_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team was updated successfully..
        /// </summary>
        public static string Team_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Team_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new team.
        /// </summary>
        public static string Team_Index_CreateNew {
            get {
                return ResourceManager.GetString("Team_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams.
        /// </summary>
        public static string Team_Index_Teams {
            get {
                return ResourceManager.GetString("Team_Index_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teams.
        /// </summary>
        public static string Team_Index_Title {
            get {
                return ResourceManager.GetString("Team_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; and &quot;{1}&quot; must have the same value..
        /// </summary>
        public static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This name has already been taken..
        /// </summary>
        public static string Validation_Duplicate_Name {
            get {
                return ResourceManager.GetString("Validation_Duplicate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; is not a valid email address..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; contains characters that can&apos;t be in a file or directory name..
        /// </summary>
        public static string Validation_FileName {
            get {
                return ResourceManager.GetString("Validation_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only characters, numbers, dots, minus and underscore are allowed for &quot;{0}&quot;..
        /// </summary>
        public static string Validation_FileName_Regex {
            get {
                return ResourceManager.GetString("Validation_FileName_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The provided regex has an error. {0}.
        /// </summary>
        public static string Validation_Invalid_Regex {
            get {
                return ResourceManager.GetString("Validation_Invalid_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; is mandatory..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; should be shorter than {1} characters..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
